import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/Components/Navbar";
import Footer from "@/Components/Footer";
import { WixClientContexProvider } from "./../Components/Context/WixContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Next Ecommerce",
  description: "Generated by Next",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WixClientContexProvider>
          <Navbar />
          <div> {children} </div>
          <Footer />
        </WixClientContexProvider>
      </body>
    </html>
  );
}
